name: GitHub Container Registry - Build and Push
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - image_ghcr: ghcr.io/${{ github.repository }}
            image_dockerhub: joejojoestar/tf-disco
            dockerfile: Dockerfile
          - image_ghcr: ghcr.io/${{ github.repository }}-autoupdate
            image_dockerhub: joejojoestar/tf-disco-autoupdate
            dockerfile: Dockerfile.autoupdate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ matrix.image_ghcr }}
            ${{ matrix.image_dockerhub }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker images
        id: push_dockerfile
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
